server:
  port: 8100
spring:
  application:
    name: currency-conversion
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://localhost:9411
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
    enabled: true
  instance:
    prefer-ip-address: true