server:
  port: 8000
spring:
  application:
    name: currency-exchange
  datasource:
    url: jdbc:h2:mem:testdb
  jpa:
    show-sql: true
  h2:
    console:
      enabled: true
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
    enabled: true
  instance:
    prefer-ip-address: true